version: "3.8"
services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    environment:
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      plugins.security.disabled: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "X9!sW4r@2025#Open"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: opensearch-dashboards
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
    ports:
      - "5601:5601"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: mangwale
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--binlog_format=ROW"
      - "--server-id=1"
      - "--binlog_row_image=FULL"
    volumes:
      - mysql-data:/var/lib/mysql

  redpanda:
    image: redpandadata/redpanda:v24.1.6
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --check=false
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=redpanda:8082
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=redpanda:33145
    ports:
      - "9092:9092"
      - "8082:8082"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  kafka-connect:
    image: debezium/connect:2.6
    container_name: kafka-connect
    depends_on:
      - redpanda
    environment:
      BOOTSTRAP_SERVERS: redpanda:9092
      REST_ADVERTISED_HOST_NAME: kafka-connect
      GROUP_ID: connect-cluster
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      PLUGIN_PATH: /kafka/connect
    ports:
      - "8083:8083"
    volumes:
      - connect-data:/data

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9001:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  adminer:
    image: adminer:4
    container_name: adminer
    depends_on:
      - mysql
    ports:
      - "8085:8080"

  frontend-proxy:
    image: nginx:alpine
    container_name: search-frontend-proxy
    volumes:
      - ./nginx/search.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/search-web/dist:/usr/share/nginx/html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.search.rule=Host(`search.mangwale.ai`)"
      - "traefik.http.routers.search.entrypoints=web,websecure"
      - "traefik.http.routers.search.tls=true"
      - "traefik.http.routers.search.tls.certresolver=letsencrypt"
      - "traefik.http.services.search.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_default
    restart: unless-stopped

volumes:
  mysql-data:
  redpanda-data:
  connect-plugins:
  connect-data:
  clickhouse-data:

networks:
  traefik_default:
    external: true
