services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      plugins.security.disabled: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "X9!sW4r@2025#Open"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
